version: 2

project_name: emission

before:
  hooks:
    - sh -c "cd ui && npm ci && npm run build"

builds:
  - main: .
    id: emission
    binary: emission
    ldflags:
      - "-s"
      - "-w"
      - "-X"
      - "main.version={{ .Version }}"
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
      - "386"
    goarm:
      - "7"
    ignore:
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: "386"
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: "386"

archives:
  - name_template: "emission-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "SHA256SUMS"
  algorithm: sha256

release:
  github:
    owner: jdel
    name: emission
  name_template: "Release {{ .Version }}"
  draft: true
  prerelease: auto

dockers:
  - use: buildx
    dockerfile: Dockerfile.goreleaser
    image_templates:
      - "ghcr.io/jdel/emission:{{ .Tag }}-amd64"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
  - use: buildx
    dockerfile: Dockerfile.goreleaser
    image_templates:
      - "ghcr.io/jdel/emission:{{ .Tag }}-arm64"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/jdel/emission:{{ .Tag }}"
    image_templates:
      - "ghcr.io/jdel/emission:{{ .Tag }}-amd64"
      - "ghcr.io/jdel/emission:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/jdel/emission:latest"
    image_templates:
      - "ghcr.io/jdel/emission:{{ .Tag }}-amd64"
      - "ghcr.io/jdel/emission:{{ .Tag }}-arm64"

brews:
  - name: emission
    directory: Formula
    repository:
      owner: jdel
      name: homebrew-tap
      token: "{{ .Env.GITHUB_APP_TOKEN }}"
    url_template: "https://github.com/jdel/emission/releases/download/{{ .Tag }}/emission-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}.tar.gz"
    homepage: "https://github.com/jdel/emission"
    description: "Spoof BitTorrent tracker announces to boost your ratio"
    skip_upload: auto
    commit_author:
      name: emission[bot]
      email: noreply@jdel.org
    test: |
      system "#{bin}/emission --help"
    install: |
      bin.install "emission"
