// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/credentials/{id}": {
            "delete": {
                "tags": [
                    "admin"
                ],
                "summary": "Remove a passkey (admin only)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Base64url credential ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/cmd.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/invite": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Create an invite link",
                "parameters": [
                    {
                        "description": "Username for the invite",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/cmd.inviteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cmd.inviteResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/invites": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "List pending invites (admin only)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/cmd.pendingInvite"
                            }
                        }
                    }
                }
            }
        },
        "/api/auth/invites/{token}": {
            "delete": {
                "tags": [
                    "admin"
                ],
                "summary": "Revoke a pending invite (admin only)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Invite token",
                        "name": "token",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/cmd.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/login/begin": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Begin passkey login",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cmd.loginChallenge"
                        }
                    }
                }
            }
        },
        "/api/auth/login/finish": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Finish passkey login",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Ceremony ID from /begin",
                        "name": "ceremony",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cmd.authResult"
                        }
                    }
                }
            }
        },
        "/api/auth/logout": {
            "post": {
                "tags": [
                    "auth"
                ],
                "summary": "Log out",
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/api/auth/me": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "List my devices",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/cmd.deviceInfo"
                            }
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "auth"
                ],
                "summary": "Delete my account",
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/api/auth/me/devices/{id}": {
            "delete": {
                "tags": [
                    "auth"
                ],
                "summary": "Remove one of my devices",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Base64url credential ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/cmd.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/register/begin": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Begin passkey registration",
                "parameters": [
                    {
                        "description": "Invite token (empty string for bootstrap)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/cmd.inviteBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cmd.registerChallenge"
                        }
                    }
                }
            }
        },
        "/api/auth/register/finish": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Finish passkey registration",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Ceremony ID from /begin",
                        "name": "ceremony",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cmd.authResult"
                        }
                    }
                }
            }
        },
        "/api/auth/status": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Authentication status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cmd.authStatusResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/users": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "List registered devices (admin only)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/cmd.deviceInfo"
                            }
                        }
                    }
                }
            }
        },
        "/api/auth/users/{username}": {
            "delete": {
                "tags": [
                    "admin"
                ],
                "summary": "Remove a user and their torrents (admin only)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/cmd.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/torrents": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "torrents"
                ],
                "summary": "List torrents",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page size (0 = all, default 10)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Case-insensitive name filter",
                        "name": "q",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cmd.pagedTorrents"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "torrents"
                ],
                "summary": "Upload a .torrent file",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Torrent file (.torrent)",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Minimum upload rate (e.g. 200K)",
                        "name": "min-speed",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Maximum upload rate (e.g. 1M)",
                        "name": "max-speed",
                        "in": "formData"
                    },
                    {
                        "type": "number",
                        "description": "Stop uploading at N × torrent size (0 = unlimited)",
                        "name": "max-ratio",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/cmd.uploadResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/cmd.errorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/cmd.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/torrents/{id}": {
            "delete": {
                "tags": [
                    "torrents"
                ],
                "summary": "Remove a torrent",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Torrent info hash (40-char hex)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/cmd.errorResponse"
                        }
                    }
                }
            },
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "torrents"
                ],
                "summary": "Update torrent upload speed",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Torrent info hash (40-char hex)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Speed settings",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/cmd.speedUpdate"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/cmd.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/cmd.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/torrents/{id}/stats": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "torrents"
                ],
                "summary": "Get torrent stats history",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Torrent info hash (40-char hex)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/seeder.StatsPoint"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/cmd.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/cmd.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/ws": {
            "get": {
                "description": "Upgrades to WebSocket. Pushes {type:\"stats\",torrents:[...]} ~1/s and {type:\"changed\"} on list changes.",
                "tags": [
                    "realtime"
                ],
                "summary": "WebSocket live stats feed",
                "responses": {}
            }
        }
    },
    "definitions": {
        "cmd.authResult": {
            "type": "object",
            "properties": {
                "authenticated": {
                    "type": "boolean"
                }
            }
        },
        "cmd.authStatusResponse": {
            "type": "object",
            "properties": {
                "authEnabled": {
                    "type": "boolean"
                },
                "authenticated": {
                    "type": "boolean"
                },
                "bootstrapAvailable": {
                    "type": "boolean"
                },
                "deviceCount": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "cmd.deviceInfo": {
            "type": "object",
            "properties": {
                "addedAt": {
                    "type": "integer"
                },
                "id": {
                    "description": "base64url credential id",
                    "type": "string"
                },
                "invitedBy": {
                    "description": "empty for the bootstrap admin",
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "cmd.errorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "cmd.inviteBody": {
            "type": "object",
            "properties": {
                "invite": {
                    "type": "string"
                }
            }
        },
        "cmd.inviteRequest": {
            "type": "object",
            "properties": {
                "username": {
                    "type": "string"
                }
            }
        },
        "cmd.inviteResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "cmd.loginChallenge": {
            "type": "object",
            "properties": {
                "ceremonyId": {
                    "type": "string"
                },
                "options": {
                    "$ref": "#/definitions/protocol.CredentialAssertion"
                }
            }
        },
        "cmd.pagedTorrents": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/seeder.Status"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "cmd.pendingInvite": {
            "type": "object",
            "properties": {
                "createdBy": {
                    "type": "string"
                },
                "expiresAt": {
                    "description": "unix ms",
                    "type": "integer"
                },
                "token": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "cmd.registerChallenge": {
            "type": "object",
            "properties": {
                "ceremonyId": {
                    "type": "string"
                },
                "options": {
                    "$ref": "#/definitions/protocol.CredentialCreation"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "cmd.speedUpdate": {
            "type": "object",
            "properties": {
                "deleteOnCap": {
                    "type": "boolean"
                },
                "maxRatio": {
                    "type": "number"
                },
                "maxSpeed": {
                    "type": "string"
                },
                "minSpeed": {
                    "type": "string"
                }
            }
        },
        "cmd.uploadResult": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "protocol.AttestationFormat": {
            "type": "string",
            "enum": [
                "packed",
                "tpm",
                "android-key",
                "android-safetynet",
                "fido-u2f",
                "apple",
                "compound",
                "none"
            ],
            "x-enum-varnames": [
                "AttestationFormatPacked",
                "AttestationFormatTPM",
                "AttestationFormatAndroidKey",
                "AttestationFormatAndroidSafetyNet",
                "AttestationFormatFIDOUniversalSecondFactor",
                "AttestationFormatApple",
                "AttestationFormatCompound",
                "AttestationFormatNone"
            ]
        },
        "protocol.AuthenticationExtensions": {
            "type": "object",
            "additionalProperties": {}
        },
        "protocol.AuthenticatorAttachment": {
            "type": "string",
            "enum": [
                "platform",
                "cross-platform"
            ],
            "x-enum-varnames": [
                "Platform",
                "CrossPlatform"
            ]
        },
        "protocol.AuthenticatorSelection": {
            "type": "object",
            "properties": {
                "authenticatorAttachment": {
                    "description": "AuthenticatorAttachment If this member is present, eligible authenticators are filtered to only\nauthenticators attached with the specified AuthenticatorAttachment enum.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/protocol.AuthenticatorAttachment"
                        }
                    ]
                },
                "requireResidentKey": {
                    "description": "RequireResidentKey this member describes the Relying Party's requirements regarding resident\ncredentials. If the parameter is set to true, the authenticator MUST create a client-side-resident\npublic key credential source when creating a public key credential.",
                    "type": "boolean"
                },
                "residentKey": {
                    "description": "ResidentKey this member describes the Relying Party's requirements regarding resident\ncredentials per Webauthn Level 2.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/protocol.ResidentKeyRequirement"
                        }
                    ]
                },
                "userVerification": {
                    "description": "UserVerification This member describes the Relying Party's requirements regarding user verification for\nthe create() operation. Eligible authenticators are filtered to only those capable of satisfying this\nrequirement.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/protocol.UserVerificationRequirement"
                        }
                    ]
                }
            }
        },
        "protocol.AuthenticatorTransport": {
            "type": "string",
            "enum": [
                "usb",
                "nfc",
                "ble",
                "smart-card",
                "hybrid",
                "internal"
            ],
            "x-enum-varnames": [
                "USB",
                "NFC",
                "BLE",
                "SmartCard",
                "Hybrid",
                "Internal"
            ]
        },
        "protocol.ConveyancePreference": {
            "type": "string",
            "enum": [
                "none",
                "indirect",
                "direct",
                "enterprise"
            ],
            "x-enum-varnames": [
                "PreferNoAttestation",
                "PreferIndirectAttestation",
                "PreferDirectAttestation",
                "PreferEnterpriseAttestation"
            ]
        },
        "protocol.CredentialAssertion": {
            "type": "object",
            "properties": {
                "mediation": {
                    "$ref": "#/definitions/protocol.CredentialMediationRequirement"
                },
                "publicKey": {
                    "$ref": "#/definitions/protocol.PublicKeyCredentialRequestOptions"
                }
            }
        },
        "protocol.CredentialCreation": {
            "type": "object",
            "properties": {
                "mediation": {
                    "$ref": "#/definitions/protocol.CredentialMediationRequirement"
                },
                "publicKey": {
                    "$ref": "#/definitions/protocol.PublicKeyCredentialCreationOptions"
                }
            }
        },
        "protocol.CredentialDescriptor": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "CredentialID The ID of a credential to allow/disallow.",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "transports": {
                    "description": "The authenticator transports that can be used.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/protocol.AuthenticatorTransport"
                    }
                },
                "type": {
                    "description": "The valid credential types.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/protocol.CredentialType"
                        }
                    ]
                }
            }
        },
        "protocol.CredentialMediationRequirement": {
            "type": "string",
            "enum": [
                "",
                "silent",
                "optional",
                "conditional",
                "required"
            ],
            "x-enum-varnames": [
                "MediationDefault",
                "MediationSilent",
                "MediationOptional",
                "MediationConditional",
                "MediationRequired"
            ]
        },
        "protocol.CredentialParameter": {
            "type": "object",
            "properties": {
                "alg": {
                    "$ref": "#/definitions/webauthncose.COSEAlgorithmIdentifier"
                },
                "type": {
                    "$ref": "#/definitions/protocol.CredentialType"
                }
            }
        },
        "protocol.CredentialType": {
            "type": "string",
            "enum": [
                "public-key"
            ],
            "x-enum-varnames": [
                "PublicKeyCredentialType"
            ]
        },
        "protocol.PublicKeyCredentialCreationOptions": {
            "type": "object",
            "properties": {
                "attestation": {
                    "$ref": "#/definitions/protocol.ConveyancePreference"
                },
                "attestationFormats": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/protocol.AttestationFormat"
                    }
                },
                "authenticatorSelection": {
                    "$ref": "#/definitions/protocol.AuthenticatorSelection"
                },
                "challenge": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "excludeCredentials": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/protocol.CredentialDescriptor"
                    }
                },
                "extensions": {
                    "$ref": "#/definitions/protocol.AuthenticationExtensions"
                },
                "hints": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/protocol.PublicKeyCredentialHints"
                    }
                },
                "pubKeyCredParams": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/protocol.CredentialParameter"
                    }
                },
                "rp": {
                    "$ref": "#/definitions/protocol.RelyingPartyEntity"
                },
                "timeout": {
                    "type": "integer"
                },
                "user": {
                    "$ref": "#/definitions/protocol.UserEntity"
                }
            }
        },
        "protocol.PublicKeyCredentialHints": {
            "type": "string",
            "enum": [
                "security-key",
                "client-device",
                "hybrid"
            ],
            "x-enum-varnames": [
                "PublicKeyCredentialHintSecurityKey",
                "PublicKeyCredentialHintClientDevice",
                "PublicKeyCredentialHintHybrid"
            ]
        },
        "protocol.PublicKeyCredentialRequestOptions": {
            "type": "object",
            "properties": {
                "allowCredentials": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/protocol.CredentialDescriptor"
                    }
                },
                "challenge": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "extensions": {
                    "$ref": "#/definitions/protocol.AuthenticationExtensions"
                },
                "hints": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/protocol.PublicKeyCredentialHints"
                    }
                },
                "rpId": {
                    "type": "string"
                },
                "timeout": {
                    "type": "integer"
                },
                "userVerification": {
                    "$ref": "#/definitions/protocol.UserVerificationRequirement"
                }
            }
        },
        "protocol.RelyingPartyEntity": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "A unique identifier for the Relying Party entity, which sets the RP ID.",
                    "type": "string"
                },
                "name": {
                    "description": "A human-palatable name for the entity. Its function depends on what the PublicKeyCredentialEntity represents:\n\nWhen inherited by PublicKeyCredentialRpEntity it is a human-palatable identifier for the Relying Party,\nintended only for display. For example, \"ACME Corporation\", \"Wonderful Widgets, Inc.\" or \"ОАО Примертех\".\n\nWhen inherited by PublicKeyCredentialUserEntity, it is a human-palatable identifier for a user account. It is\nintended only for display, i.e., aiding the user in determining the difference between user accounts with similar\ndisplayNames. For example, \"alexm\", \"alex.p.mueller@example.com\" or \"+14255551234\".",
                    "type": "string"
                }
            }
        },
        "protocol.ResidentKeyRequirement": {
            "type": "string",
            "enum": [
                "discouraged",
                "preferred",
                "required"
            ],
            "x-enum-varnames": [
                "ResidentKeyRequirementDiscouraged",
                "ResidentKeyRequirementPreferred",
                "ResidentKeyRequirementRequired"
            ]
        },
        "protocol.UserEntity": {
            "type": "object",
            "properties": {
                "displayName": {
                    "description": "A human-palatable name for the user account, intended only for display.\nFor example, \"Alex P. Müller\" or \"田中 倫\". The Relying Party SHOULD let\nthe user choose this, and SHOULD NOT restrict the choice more than necessary.",
                    "type": "string"
                },
                "id": {
                    "description": "ID is the user handle of the user account entity. To ensure secure operation,\nauthentication and authorization decisions MUST be made on the basis of this id\nmember, not the displayName nor name members. See Section 6.1 of\n[RFC8266](https://www.w3.org/TR/webauthn/#biblio-rfc8266)."
                },
                "name": {
                    "description": "A human-palatable name for the entity. Its function depends on what the PublicKeyCredentialEntity represents:\n\nWhen inherited by PublicKeyCredentialRpEntity it is a human-palatable identifier for the Relying Party,\nintended only for display. For example, \"ACME Corporation\", \"Wonderful Widgets, Inc.\" or \"ОАО Примертех\".\n\nWhen inherited by PublicKeyCredentialUserEntity, it is a human-palatable identifier for a user account. It is\nintended only for display, i.e., aiding the user in determining the difference between user accounts with similar\ndisplayNames. For example, \"alexm\", \"alex.p.mueller@example.com\" or \"+14255551234\".",
                    "type": "string"
                }
            }
        },
        "protocol.UserVerificationRequirement": {
            "type": "string",
            "enum": [
                "required",
                "preferred",
                "discouraged"
            ],
            "x-enum-comments": {
                "VerificationPreferred": "This is the default."
            },
            "x-enum-descriptions": [
                "",
                "This is the default.",
                ""
            ],
            "x-enum-varnames": [
                "VerificationRequired",
                "VerificationPreferred",
                "VerificationDiscouraged"
            ]
        },
        "seeder.StatsPoint": {
            "type": "object",
            "properties": {
                "l": {
                    "description": "total leechers across all trackers",
                    "type": "integer"
                },
                "r": {
                    "description": "simulated upload rate, bytes/sec",
                    "type": "integer"
                },
                "t": {
                    "description": "unix milliseconds",
                    "type": "integer"
                }
            }
        },
        "seeder.Status": {
            "type": "object",
            "properties": {
                "addedAt": {
                    "description": "unix milliseconds",
                    "type": "integer"
                },
                "capped": {
                    "description": "true when the ratio cap has been reached",
                    "type": "boolean"
                },
                "deleteOnCap": {
                    "description": "remove the torrent automatically when capped",
                    "type": "boolean"
                },
                "id": {
                    "description": "info hash, hex",
                    "type": "string"
                },
                "location": {
                    "description": ".torrent path, relative to the watched root",
                    "type": "string"
                },
                "maxRateBytesPerSec": {
                    "description": "configured ceiling",
                    "type": "integer"
                },
                "maxRatio": {
                    "description": "upload cap as a multiple of torrent size (0 = unlimited)",
                    "type": "number"
                },
                "minRateBytesPerSec": {
                    "description": "configured floor",
                    "type": "integer"
                },
                "name": {
                    "description": "torrent display name",
                    "type": "string"
                },
                "rateBytesPerSec": {
                    "type": "integer"
                },
                "sizeBytes": {
                    "type": "integer"
                },
                "trackers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/seeder.TrackerStatus"
                    }
                },
                "uploadedBytes": {
                    "type": "integer"
                }
            }
        },
        "seeder.TrackerStatus": {
            "type": "object",
            "properties": {
                "intervalSec": {
                    "type": "integer"
                },
                "leechers": {
                    "type": "integer"
                },
                "minIntervalSec": {
                    "type": "integer"
                },
                "nextAnnounceAt": {
                    "description": "unix ms, 0 if unknown",
                    "type": "integer"
                },
                "seeders": {
                    "type": "integer"
                },
                "status": {
                    "description": "\"ok\" | \"failing\" | \"pending\"",
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "webauthncose.COSEAlgorithmIdentifier": {
            "type": "integer",
            "enum": [
                -7,
                -8,
                -9,
                -19,
                -35,
                -36,
                -37,
                -38,
                -39,
                -47,
                -48,
                -49,
                -50,
                -51,
                -52,
                -257,
                -258,
                -259,
                -65535
            ],
            "x-enum-varnames": [
                "AlgES256",
                "AlgEdDSA",
                "AlgESP256",
                "AlgEd25519",
                "AlgES384",
                "AlgES512",
                "AlgPS256",
                "AlgPS384",
                "AlgPS512",
                "AlgES256K",
                "AlgMLDSA44",
                "AlgMLDSA65",
                "AlgMLDSA87",
                "AlgESP384",
                "AlgESP512",
                "AlgRS256",
                "AlgRS384",
                "AlgRS512",
                "AlgRS1"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
